# Generated by Django 5.1.7 on 2025-04-30 13:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprises', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('lieu', models.CharField(max_length=100)),
                ('duree', models.CharField(max_length=50)),
                ('date_limite', models.DateField()),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offres', to='entreprises.entreprise')),
            ],
        ),
    ]
