# Generated by Django 5.1.7 on 2025-04-30 15:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprises', '0002_offre'),
        ('etudiants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lettre_motivation', models.TextField()),
                ('cv', models.FileField(upload_to='cvs/')),
                ('date_candidature', models.DateTimeField(default=django.utils.timezone.now)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etudiants.etudiant')),
                ('offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entreprises.offre')),
            ],
        ),
    ]
