# Generated by Django 5.1.7 on 2025-05-14 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprises', '0004_alter_candidature_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidature',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée')], default='en_attente', max_length=20),
        ),
    ]
