# Generated by Django 5.1.7 on 2025-05-14 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entreprises', '0005_candidature_statut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidature',
            name='statut',
        ),
    ]
